### ISSUE TITLE
Update to 19.08

### ISSUE THREAD

**Issue by dac73** [flathub/org.freedesktop.Sdk.Extension.dotnet#2]
Blocks https://github.com/flathub/com.visualstudio.code/pull/111

**Comment by barthalion** [comment]
Build in progress: https://flathub.org/builds/#/builders/32/builds/9378

**Comment by barthalion** [comment]
Take #2: https://flathub.org/builds/#/builders/32/builds/9396

**Comment by barthalion** [comment]
Done.

**Comment by dac73** [comment]
It's still not available, perhaps because UpdateRepo failed?

**Comment by refi64** [comment]
Trying it again: https://flathub.org/builds/#/builders/32/builds/9665
